apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonita-deployment
  labels:
    app: bonita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bonita
  template:
    metadata:
      labels:
        app: bonita
    spec:
      containers:
        - name: bonita
          image: docker.io/library/bonita-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          env:
            - name: BIZ_DB_NAME
              value: business_data
            - name: BIZ_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: BIZ_DB_PASS
            - name: BIZ_DB_USER
              value: business_data
            - name: DB_HOST
              value: postgres-service
            - name: DB_NAME
              value: bonita
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: DB_PASS
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: bonita
            - name: DB_VENDOR
              value: postgres
            - name: TENANT_LOGIN
              value: tech_user
            - name: TENANT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: TENANT_PASSWORD
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: bonita-service
spec:
  type: NodePort
  selector:
    app: bonita
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30200
