apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonita-h2-deployment
  labels:
    app: bonita-h2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bonita-h2
  template:
    metadata:
      labels:
        app: bonita-h2
    spec:
      containers:
        - name: bonita-h2
          image: bonita:2023.2
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          env:
            - name: BIZ_DB_NAME
              value: business_data
            - name: BIZ_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: BIZ_DB_PASS
            - name: BIZ_DB_USER
              value: business_data
            - name: DB_NAME
              value: bonita
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: DB_PASS
            - name: DB_USER
              value: bonita
            - name: DB_VENDOR
              value: h2
            - name: TENANT_LOGIN
              value: tech_user
            - name: TENANT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bonita-secret
                  key: TENANT_PASSWORD
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: bonita-h2-service
spec:
  type: NodePort
  selector:
    app: bonita-h2
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30300
